<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        // Custom business permissions (not auto-generated by Shield)
        $customPermissions = [
            // Sales Manager
            'visit_assignments.manage', 'customers.approve', 'customers.view_all',
            'pricing.set_range', 'alarms.view_all', 'alarms.respond',
            'complaints.manage', 'reports.sales', 'reports.visits', 'reports.view',
            'invoices.view_all', 'invoices.approve', 'purchase_requests.veto',
            'van_transfers.approve',
            // Accounts
            'products.manage_prices', 'products.view_cost', 'products.manage_cost',
            'goods_in_transit.manage_landed_cost',
            'invoices.cancel', 'payments.view_all', 'reports.financial',
            'tax_templates.manage',
            // Purchasing
            'purchase_requests.view_all', 'supplier_quotations.manage',
            'purchase_orders.manage', 'goods_in_transit.manage',
            'goods_in_transit.receive', 'reports.purchasing',
            // Warehouse Keeper
            'stock.import', 'stock.adjust', 'stock.export',
            'batches.manage', 'reports.stock',
            // Executive
            'alarms.view', 'reports.dashboard_view', 'reports.sales_view',
            'reports.visits_view', 'reports.stock_view', 'reports.intercompany_view',
            // Rep
            'sessions.manage', 'visits.view_assigned', 'visits.execute',
            'visits.custom', 'customers.add', 'customers.view_own',
            'products.view', 'products.view_stock', 'pricing.request',
            'pricing.negotiate', 'proformas.create', 'invoices.create',
            'invoices.view_own', 'payments.collect', 'returns.create',
            'expenses.log', 'purchase_requests.submit', 'alarms.flag_out_of_stock',
            'complaints.submit', 'cashbox.view', 'van_transfers.request',
            // HR administration
            'users.manage', 'roles.assign', 'routes.assign',
            // Stock / Purchasing
            'stock.view', 'suppliers.manage',
        ];

        foreach ($customPermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // Shield-generated resource permissions (action:resource format)
        $shieldPermissions = [
            'company' => ['view_any', 'view', 'create', 'update', 'delete'],
            'user' => ['view_any', 'view', 'create', 'update', 'delete'],
            'customer' => ['view_any', 'view', 'create', 'update', 'delete'],
            'task' => ['view_any', 'view', 'create', 'update', 'delete'],
            'alarm' => ['view_any', 'view', 'create', 'update', 'delete'],
            'batch' => ['view_any', 'view', 'create', 'update', 'delete'],
            'invoice' => ['view_any', 'view', 'create', 'update', 'delete'],
            'proforma_invoice' => ['view_any', 'view', 'create', 'update', 'delete'],
            'return_record' => ['view_any', 'view', 'create', 'update', 'delete'],
            'payment' => ['view_any', 'view', 'create', 'update', 'delete'],
            'expense' => ['view_any', 'view', 'create', 'update', 'delete'],
            'cash_reconciliation' => ['view_any', 'view', 'create', 'update', 'delete'],
            'product' => ['view_any', 'view', 'create', 'update', 'delete'],
            'product_price' => ['view_any', 'view', 'create', 'update', 'delete'],
            'stock' => ['view_any', 'view', 'create', 'update', 'delete'],
            'goods_in_transit' => ['view_any', 'view', 'create', 'update', 'delete'],
            'purchase_request' => ['view_any', 'view', 'create', 'update', 'delete'],
            'purchase_order' => ['view_any', 'view', 'create', 'update', 'delete'],
            'van_transfer' => ['view_any', 'view', 'create', 'update', 'delete'],
            'route' => ['view_any', 'view', 'create', 'update', 'delete'],
            'sales_target' => ['view_any', 'view', 'create', 'update', 'delete'],
            'daily_visit_assignment' => ['view_any', 'view', 'create', 'update', 'delete'],
            'price_quotation_request' => ['view_any', 'view', 'create', 'update', 'delete'],
            'complaint' => ['view_any', 'view', 'create', 'update', 'delete'],
        ];

        foreach ($shieldPermissions as $resource => $actions) {
            foreach ($actions as $action) {
                Permission::firstOrCreate(['name' => "{$action}:{$resource}", 'guard_name' => 'web']);
            }
        }

        // Shield-generated page permissions
        $pagePermissions = [
            'view:reports_page', 'view:supplier_comparison', 'view:collect_payment',
            'view:rep_live_map', 'view:customer_map',
            'view:admin_preferences', 'view:api_tokens', 'view:stock_import',
        ];

        foreach ($pagePermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // Shield-generated widget permissions
        $widgetPermissions = [
            'view:visits_today_widget', 'view:pending_quotations_widget',
            'view:open_alarms_widget', 'view:sales_today_widget',
            'view:outstanding_balance_widget', 'view:rep_performance_widget',
        ];

        foreach ($widgetPermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // admin & super_admin get EVERYTHING
        $allPerms = Permission::all();

        $rolePermissions = [
            'super_admin' => $allPerms->pluck('name')->toArray(),
            'admin' => $allPerms->pluck('name')->toArray(),

            'sales_manager' => [
                // Resources
                'view_any:customer', 'view:customer', 'create:customer', 'update:customer',
                'view_any:invoice', 'view:invoice', 'update:invoice',
                'view_any:proforma_invoice', 'view:proforma_invoice', 'create:proforma_invoice', 'update:proforma_invoice',
                'view_any:return_record', 'view:return_record', 'create:return_record', 'update:return_record',
                'view_any:payment', 'view:payment', 'create:payment', 'update:payment',
                'view_any:expense', 'view:expense', 'create:expense',
                'view_any:cash_reconciliation', 'view:cash_reconciliation', 'update:cash_reconciliation',
                'view_any:stock', 'view:stock', 'update:stock',
                'view_any:batch', 'view:batch',
                'view_any:goods_in_transit', 'view:goods_in_transit',
                'view_any:purchase_request', 'view:purchase_request', 'create:purchase_request', 'update:purchase_request',
                'view_any:purchase_order', 'view:purchase_order',
                'view_any:van_transfer', 'view:van_transfer', 'create:van_transfer',
                'view_any:alarm', 'view:alarm', 'update:alarm',
                'view_any:task', 'view:task', 'create:task', 'update:task',
                'view_any:sales_target', 'view:sales_target', 'create:sales_target', 'update:sales_target', 'delete:sales_target',
                'view_any:route', 'view:route', 'create:route', 'update:route', 'delete:route',
                'view_any:daily_visit_assignment', 'view:daily_visit_assignment', 'create:daily_visit_assignment', 'update:daily_visit_assignment',
                'view_any:price_quotation_request', 'view:price_quotation_request', 'create:price_quotation_request', 'update:price_quotation_request',
                'view_any:complaint', 'view:complaint', 'create:complaint', 'update:complaint',
                // Pages
                'view:reports_page', 'view:collect_payment',
                // Widgets
                'view:visits_today_widget', 'view:pending_quotations_widget', 'view:open_alarms_widget',
                'view:sales_today_widget', 'view:outstanding_balance_widget', 'view:rep_performance_widget',
                // Custom
                'visit_assignments.manage', 'customers.approve', 'customers.view_all',
                'pricing.set_range', 'alarms.view_all', 'alarms.respond',
                'complaints.manage', 'reports.sales', 'reports.visits', 'reports.view',
                'invoices.view_all', 'invoices.approve', 'purchase_requests.veto',
                'van_transfers.approve',
            ],

            'accounts' => [
                // Resources
                'view_any:customer',
                'view_any:invoice', 'view:invoice', 'update:invoice',
                'view_any:proforma_invoice', 'view:proforma_invoice',
                'view_any:return_record', 'view:return_record',
                'view_any:payment', 'view:payment',
                'view_any:expense', 'view:expense',
                'view_any:cash_reconciliation', 'view:cash_reconciliation', 'update:cash_reconciliation',
                'view_any:stock', 'view:stock',
                'view_any:batch',
                'view_any:goods_in_transit',
                'view_any:purchase_request',
                'view_any:purchase_order',
                'view_any:van_transfer',
                'view_any:alarm',
                // Pages
                'view:reports_page', 'view:collect_payment',
                // Widgets
                'view:visits_today_widget', 'view:pending_quotations_widget', 'view:open_alarms_widget',
                'view:sales_today_widget', 'view:outstanding_balance_widget',
                // Custom
                'products.manage_prices', 'products.view_cost', 'products.manage_cost',
                'goods_in_transit.manage_landed_cost',
                'invoices.view_all', 'invoices.cancel', 'payments.view_all', 'reports.financial',
                'customers.view_all', 'tax_templates.manage',
            ],

            'purchasing' => [
                // Resources
                'view_any:customer',
                'view_any:batch', 'view:batch', 'create:batch', 'update:batch',
                'view_any:goods_in_transit', 'view:goods_in_transit', 'create:goods_in_transit', 'update:goods_in_transit',
                'view_any:purchase_request', 'view:purchase_request', 'update:purchase_request',
                'view_any:purchase_order', 'view:purchase_order',
                'view_any:product',
                // Pages
                'view:supplier_comparison',
                // Custom
                'purchase_requests.view_all', 'supplier_quotations.manage',
                'purchase_orders.manage', 'goods_in_transit.manage',
                'goods_in_transit.receive', 'suppliers.manage',
                'reports.purchasing',
            ],

            'warehouse_keeper' => [
                // Resources
                'view_any:batch', 'view:batch', 'create:batch', 'update:batch',
                'view_any:goods_in_transit', 'view:goods_in_transit', 'create:goods_in_transit', 'update:goods_in_transit',
                'view_any:stock', 'view:stock',
                'view_any:van_transfer', 'view:van_transfer', 'create:van_transfer',
                // Custom
                'stock.import', 'stock.adjust', 'stock.export',
                'batches.manage', 'goods_in_transit.receive', 'reports.stock',
            ],

            'executive' => [
                // Resources
                'view_any:company', 'view:company',
                'view_any:alarm', 'view:alarm', 'update:alarm',
                'view_any:task', 'view:task',
                'view_any:sales_target', 'view:sales_target',
                // Custom
                'alarms.view', 'reports.dashboard_view', 'reports.sales_view',
                'reports.visits_view', 'reports.stock_view', 'reports.intercompany_view',
            ],

            'sales_rep' => [
                // Custom (reps use PWA, not Filament panel)
                'sessions.manage', 'visits.view_assigned', 'visits.execute',
                'visits.custom', 'customers.add', 'customers.view_own',
                'products.view', 'products.view_stock', 'pricing.request',
                'pricing.negotiate', 'proformas.create', 'invoices.create',
                'invoices.view_own', 'payments.collect', 'returns.create',
                'expenses.log', 'purchase_requests.submit', 'alarms.flag_out_of_stock',
                'complaints.submit', 'cashbox.view', 'van_transfers.request',
                // Shield resource permissions required by services that gate on
                // can('create:...') / can('update:...') instead of custom names.
                'create:invoice', 'create:return_record',
            ],

            'rep' => [
                // Minimal role for rep panel (PWA) access — mirrors sales_rep
                'sessions.manage', 'visits.view_assigned', 'visits.execute',
                'visits.custom', 'customers.add', 'customers.view_own',
                'products.view', 'products.view_stock', 'pricing.request',
                'pricing.negotiate', 'proformas.create', 'invoices.create',
                'invoices.view_own', 'payments.collect', 'returns.create',
                'expenses.log', 'purchase_requests.submit', 'alarms.flag_out_of_stock',
                'complaints.submit', 'cashbox.view', 'van_transfers.request',
                // Shield resource permissions required by services (see sales_rep).
                'create:invoice', 'create:return_record',
            ],

            'hr_admin' => [
                // Resources
                'view_any:user', 'view:user', 'create:user', 'update:user', 'delete:user',
                // Custom
                'users.manage', 'roles.assign', 'routes.assign',
            ],

            'system_viewer' => [
                // Resources (read-only)
                'view_any:customer',
                'view_any:invoice', 'view:invoice',
                'view_any:payment', 'view:payment',
                'view_any:stock', 'view:stock',
                'view_any:batch',
                'view_any:goods_in_transit',
                'view_any:purchase_request',
                'view_any:purchase_order',
                'view_any:van_transfer',
                'view_any:alarm', 'view:alarm',
                // Pages
                'view:reports_page',
                // Widgets
                'view:visits_today_widget', 'view:pending_quotations_widget', 'view:open_alarms_widget',
                'view:sales_today_widget', 'view:outstanding_balance_widget',
                // Custom
                'customers.view_all', 'stock.view', 'invoices.view_all',
                'payments.view_all', 'reports.view', 'reports.sales',
                'reports.visits', 'reports.financial', 'reports.stock',
                'reports.purchasing', 'alarms.view',
            ],
        ];

        foreach ($rolePermissions as $roleName => $perms) {
            $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
            $role->syncPermissions($perms);
        }
    }
}
