[deploy]
preDeployCommand = "php artisan migrate --force && php artisan db:seed --class=DemoSeeder --force"
startCommand = "/app/docker/start-container.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 2
